name: Test
on:
  push:
    branches: [ staging ]
    paths:
      - 'tests/**'
  pull_request:
    branches: [ review ]
    paths:
      - 'tests/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx hardhat compile
    - run: npx hardhat test test/accessregistryTest.js
    - run: npx hardhat test test/comptrollerTest.js
    - run: npx hardhat test test/depositTest.js
    - run: npx hardhat test test/diamondTest.js
    - run: npx hardhat test test/loanTest.js
    - run: npx hardhat test test/tokenlistTest.js


